sector_keywords = {
    'Bao bì và vật chứa': ['bao bì và vật chứa', 'chai lọ', 'hộp', 'vỏ hộp', 'đóng gói'],
    'Bán lẻ chuyên doanh': ['bán lẻ chuyên doanh', 'bán lẻ'],
    'Bán lẻ đa dạng': ['bán lẻ đa dạng', 'bán lẻ'],
    'Bảo hiểm': ['bảo hiểm', 'bảo hiểm nhân thọ', 'bảo vệ', 'rủi ro', 'tai nạn'],
    'Bất động sản đa dạng': ['bất động sản đa dạng', 'chung cư', 'khu công nghiệp', 'nhà đất', 'địa ốc'],
    'Dược phẩm': ['bệnh viện', 'dược phẩm', 'kháng sinh', 'thuốc', 'y tế'],
    'Dầu khí': ['dầu', 'dầu khí', 'khí đốt', 'nhiên liệu', 'xăng', 'xăng dầu'],
    'Dịch vụ CNTT': ['dịch vụ cntt'],
    'Dịch vụ bất động sản': ['chung cư', 'dịch vụ bất động sản', 'khu công nghiệp', 'nhà đất', 'địa ốc'],
    'Dịch vụ chuyên nghiệp': ['dịch vụ chuyên nghiệp'],
    'Dịch vụ tiêu dùng khác': ['dịch vụ tiêu dùng khác'],
    'Dịch vụ tài chính': ['chứng khoán', 'dịch vụ tài chính', 'sàn giao dịch', 'trái phiếu', 'đầu tư'],
    'Dịch vụ viễn thông không dây': ['báo chí', 'cáp quang', 'dịch vụ viễn thông không dây', 'internet', 'truyền hình'],
    'Dịch vụ viễn thông đa dạng': ['báo chí', 'cáp quang', 'dịch vụ viễn thông đa dạng', 'internet', 'truyền hình'],
    'Dịch vụ và thiết bị thương mại': ['bán buôn', 'bán lẻ', 'cửa hàng', 'dịch vụ và thiết bị thương mại'],
    'Gas sinh hoạt': ['bình gas', 'gas sinh hoạt', 'khí đốt', 'nấu ăn'],
    'Giải trí': ['ca sĩ', 'gameshow', 'giải trí', 'phim ảnh', 'âm nhạc'],
    'Gỗ và giấy': ['gỗ và giấy', 'gỗ xẻ', 'gỗ ép', 'đồ nội thất'],
    'Hàng tiêu dùng lâu bền': ['hàng tiêu dùng lâu bền'],
    'Hãng hàng không chở khách': ['hãng hàng không chở khách'],
    'Hóa chất': ['acid', 'chất tẩy', 'hóa chất', 'hóa học', 'phân bón', 'thuốc nhuộm'],
    'Hạ tầng giao thông': ['hạ tầng giao thông'],
    'Khai khoáng và luyện kim': ['khai khoáng và luyện kim'],
    'Khách sạn, nhà hàng và giải trí': ['ca sĩ', 'gameshow', 'khách sạn, nhà hàng và giải trí', 'phim ảnh', 'âm nhạc'],
    'Kỹ thuật xây dựng': ['kỹ thuật xây dựng'],
    'Linh kiện xe': ['linh kiện', 'linh kiện xe', 'xe máy', 'ô tô', 'động cơ'],
    'Máy móc công nghiệp': ['máy khoan', 'máy móc công nghiệp', 'máy tiện', 'thiết bị cơ khí'],
    'Ngân hàng': ['cho vay', 'gửi tiết kiệm', 'lãi suất', 'ngân hàng', 'tín dụng', 'vay'],
    'Nhà phân phối': ['nhà phân phối'],
    'Nước': ['cấp nước', 'nước sạch', 'xử lý nước'],
    'Phát điện độc lập và điện tái tạo': ['phát điện độc lập và điện tái tạo', 'trạm biến áp', 'điện lực', 'điện năng'],
    'Phân phối hàng công nghiệp': ['phân phối hàng công nghiệp'],
    'Phần cứng, bộ lưu trữ và thiết bị ngoại vi': ['phần cứng, bộ lưu trữ và thiết bị ngoại vi'],
    'Phần mềm': ['phần mềm'],
    'Quản lý và phát triển bất động sản': ['chung cư', 'khu công nghiệp', 'nhà đất', 'quản lý và phát triển bất động sản', 'địa ốc'],
    'Sản phẩm chăm sóc cá nhân': ['sản phẩm chăm sóc cá nhân'],
    'Sản phẩm chăm sóc gia đình': ['sản phẩm chăm sóc gia đình'],
    'Sản phẩm giải trí': ['ca sĩ', 'gameshow', 'phim ảnh', 'sản phẩm giải trí', 'âm nhạc'],
    'Sản phẩm xây dựng': ['sản phẩm xây dựng'],
    'Thiết bị viễn thông': ['báo chí', 'cáp quang', 'internet', 'thiết bị viễn thông', 'truyền hình'],
    'Thiết bị và dịch vụ năng lượng': [
        "giàn khoan", "thiết bị khoan", "dầu khí ngoài khơi", "hệ thống đường ống",
        "thiết bị khai thác", "hệ thống nén khí", "hệ thống bơm", "turbine",
        "bộ trao đổi nhiệt", "máy phát điện", "trạm nén", "cơ điện năng lượng",

        "dịch vụ khoan", "bảo trì thiết bị", "dịch vụ vận hành", "kỹ thuật giếng khoan",
        "kiểm định an toàn", "dịch vụ địa vật lý", "thi công đường ống",
        "sửa chữa giàn khoan", "hỗ trợ kỹ thuật",

        "thăm dò dầu khí", "sản xuất dầu thô", "mỏ khí đốt", "năng lượng tái tạo",
        "nhà máy lọc dầu", "chuỗi cung ứng năng lượng", "năng lượng hạ nguồn", "năng lượng thượng nguồn",

        "hợp đồng EPC", "đầu tư công trình năng lượng", "M&A ngành năng lượng",
        "đấu thầu thiết bị", "dự án năng lượng", "trúng thầu", "gói thầu",

        "PV Drilling", "Schlumberger", "Halliburton", "Baker Hughes", "PTSC",
        "tổng thầu EPC", "nhà cung cấp dịch vụ giếng khoan",

        "sản lượng khai thác", "giá dầu", "chi phí khai thác", "nhu cầu tiêu thụ",
        "tăng vốn đầu tư", "giảm vốn đầu tư", "dừng hoạt động giàn khoan",
        "khủng hoảng năng lượng", "thiếu hụt thiết bị"
        ],
    'Thiết bị và vật tư chăm sóc sức khỏe': ['thiết bị và vật tư chăm sóc sức khỏe'],
    'Thiết bị điện': ['bóng đèn', 'công tắc', 'dây điện', 'thiết bị điện', 'ổ cắm'],
    'Thuốc lá': ['thuốc lá'],
    'Thương mại hàng thiết yếu': ['bán buôn', 'bán lẻ', 'cửa hàng', 'thương mại hàng thiết yếu'],
    'Thương mại và dịch vụ chăm sóc sức khỏe': ['bán buôn', 'bán lẻ', 'cửa hàng', 'thương mại và dịch vụ chăm sóc sức khỏe'],
    'Thị trường vốn': ['chứng khoán', 'sàn giao dịch', 'thị trường vốn', 'trái phiếu', 'đầu tư'],
    'Thời trang và dệt may': ['dệt', 'may mặc', 'quần áo', 'thời trang', 'thời trang và dệt may', 'vải'],
    'Thực phẩm': ['chế biến thực phẩm', 'nông sản', 'rau củ', 'thịt cá', 'thực phẩm', 'đồ ăn'],
    'Tiện tích tổng hợp': ['tiện tích tổng hợp'],
    'Truyền thông': ['báo chí', 'cáp quang', 'internet', 'truyền hình', 'truyền thông'],
    'Tín dụng phi ngân hàng': ['cho vay', 'gửi tiết kiệm', 'lãi suất', 'tín dụng', 'tín dụng phi ngân hàng', 'vay'],
    'Tập đoàn đa ngành': ['tập đoàn đa ngành'],
    'Vận tải biển': ['container', 'giao hàng', 'kho bãi', 'vận chuyển', 'vận tải biển'],
    'Vận tải mặt đất': ['container', 'giao hàng', 'kho bãi', 'vận chuyển', 'vận tải mặt đất'],
    'Vận tải và logistics hàng không': ['container', 'giao hàng', 'kho bãi', 'vận chuyển', 'vận tải và logistics hàng không'],
    'Vật liệu xây dựng': ['cát', 'gạch', 'sắt thép', 'vật liệu xây dựng', 'xi măng', 'đá xây dựng'],
    'Xe': ['linh kiện', 'xe', 'xe máy', 'ô tô', 'động cơ'],
    'Điện': ['trạm biến áp', 'điện', 'điện lực', 'điện năng'],
    'Điện tử': ['trạm biến áp', 'điện lực', 'điện năng', 'điện tử'],
    'Đồ uống': ['đồ uống'],
}